/**
 * M3 — Phase 2 Gate: agent + workflow seeding verification.
 *
 * After kernel install of the CRM-shaped fixture, the framework's
 * agents/workflows tables (and the CRM's app-owned pipeline tables)
 * carry every expected row.
 */
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync, appendFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { sql } from "drizzle-orm";
import { Hono } from "hono";

import {
  createAppRouteRegistry,
  createKernelInstallContext,
} from "@boringos/control-plane";
import type { AppManifest } from "@boringos/app-sdk";
import { defineApp } from "@boringos/app-sdk";
import { InstallRuntime } from "@boringos/shell/runtime/install-runtime.js";

const RESULTS_PATH = join(
  new URL(".", import.meta.url).pathname,
  "..",
  "docs",
  "tests",
  "phase2-gate-results.md",
);

let dataDir: string;
let conn: { db: any; close(): Promise<void> };
let tenantId: string;
let bundleDir: string;

beforeAll(async () => {
  const { createDatabase, createMigrationManager } = await import("@boringos/db");
  dataDir = mkdtempSync(join(tmpdir(), "bos-m3-"));
  conn = await createDatabase({
    embedded: true,
    dataDir: join(dataDir, "pg"),
    port: 5587,
  });
  await createMigrationManager(conn.db).apply();
  const inserted = await conn.db.execute(sql`
    INSERT INTO tenants (name, slug) VALUES ('M3', 'm3-test') RETURNING id
  `);
  tenantId = (inserted as any[])[0].id as string;

  bundleDir = mkdtempSync(join(tmpdir(), "bos-m3-bundle-"));
  mkdirSync(join(bundleDir, "schema"), { recursive: true });
  writeFileSync(
    join(bundleDir, "schema", "001_init.sql"),
    `
      CREATE TABLE IF NOT EXISTS m3_crm_pipelines (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        tenant_id UUID NOT NULL,
        name TEXT NOT NULL,
        is_default BOOLEAN NOT NULL DEFAULT false
      );
      CREATE TABLE IF NOT EXISTS m3_crm_pipeline_stages (
        id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
        pipeline_id UUID NOT NULL,
        name TEXT NOT NULL,
        sort_order INTEGER NOT NULL DEFAULT 0
      );
    `,
    "utf8",
  );
}, 120_000);

afterAll(async () => {
  await conn?.close();
  if (dataDir) rmSync(dataDir, { recursive: true, force: true });
  if (bundleDir) rmSync(bundleDir, { recursive: true, force: true });
});

const crmManifest: AppManifest = {
  kind: "app",
  id: "crm",
  version: "0.0.1",
  name: "CRM",
  description: "M3 fixture",
  publisher: { name: "BoringOS", verified: true },
  minRuntime: "1.0.0",
  license: "BUSL-1.1",
  hosting: "in-process",
  schema: "schema",
  entityTypes: [],
  ui: { entry: "dist/ui.js" },
  capabilities: ["agents:register", "workflows:register"],
};

const expectedAgentNames = [
  "Company Enrichment",
  "Contact Enrichment",
  "CRM Email Lens",
  "Deal Analyst",
  "Follow-up Writer",
];

const expectedWorkflowNames = ["Email Sync", "Calendar Check"];

const stageNames = [
  "Qualified",
  "Discovery",
  "Demo",
  "Proposal",
  "Negotiation",
  "Closed Won",
  "Closed Lost",
];

function appendReport(block: string) {
  const dir = dirname(RESULTS_PATH);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  if (!existsSync(RESULTS_PATH)) {
    writeFileSync(
      RESULTS_PATH,
      "# Phase 2 Gate — Test Results\n\nAuto-generated by the M1-M5 vitest suite.\n",
    );
  }
  appendFileSync(RESULTS_PATH, block);
}

describe("Phase 2 Gate — agent + workflow seeding (M3)", () => {
  it("install lands all 5 CRM agents, the 2 cron workflows, and the 7-stage default pipeline", async () => {
    const coreApp = new Hono();
    const routeRegistry = createAppRouteRegistry();
    routeRegistry.attachTo(coreApp);
    const shellRuntime = new InstallRuntime();

    const kernel = createKernelInstallContext({
      db: conn.db,
      routeRegistry,
      slotRuntime: {
        installApp: (a) => shellRuntime.installApp(a),
        uninstallApp: (id) => shellRuntime.uninstallApp(id),
      },
      events: { emit: () => {} },
    });

    await kernel.installApp({
      manifest: crmManifest,
      tenantId,
      bundleDir,
      definition: defineApp({
        id: "crm",
        agents: [
          { id: "crm.email-lens", name: "CRM Email Lens", persona: "researcher", runtime: "claude" },
          { id: "crm.contact-enrichment", name: "Contact Enrichment", persona: "researcher", runtime: "claude" },
          { id: "crm.company-enrichment", name: "Company Enrichment", persona: "researcher", runtime: "claude" },
          { id: "crm.deal-analyst", name: "Deal Analyst", persona: "researcher", runtime: "claude" },
          { id: "crm.follow-up-writer", name: "Follow-up Writer", persona: "researcher", runtime: "claude" },
        ],
        workflows: [
          {
            id: "crm.email-ingest",
            name: "Email Sync",
            blocks: [{ id: "trigger", name: "trigger", type: "trigger", config: {} }],
            edges: [],
            triggers: [{ type: "cron", cron: "*/15 * * * *" }],
          },
          {
            id: "crm.calendar-check",
            name: "Calendar Check",
            blocks: [{ id: "trigger", name: "trigger", type: "trigger", config: {} }],
            edges: [],
            triggers: [{ type: "cron", cron: "*/30 * * * *" }],
          },
        ],
        onTenantCreated: async (ctx) => {
          const tx = ctx.db as unknown as { execute: (q: any) => Promise<unknown> };
          await tx.execute(sql`
            INSERT INTO m3_crm_pipelines (tenant_id, name, is_default)
            VALUES (${ctx.tenantId}, 'Sales Pipeline', true)
          `);
          const rows = (await tx.execute(sql`
            SELECT id FROM m3_crm_pipelines
            WHERE tenant_id = ${ctx.tenantId} AND is_default = true
            ORDER BY name LIMIT 1
          `)) as Array<{ id: string }>;
          const pipelineId = rows[0]?.id;
          if (!pipelineId) return;
          for (let i = 0; i < stageNames.length; i += 1) {
            await tx.execute(sql`
              INSERT INTO m3_crm_pipeline_stages (pipeline_id, name, sort_order)
              VALUES (${pipelineId}, ${stageNames[i]}, ${i})
            `);
          }
        },
      }),
    });

    // 5 agents — set comparison (Postgres + JS sort orders differ on
    // mixed-case names like "CRM Email Lens" vs "Company Enrichment").
    const agentRows = (await conn.db.execute(sql`
      SELECT name FROM agents
      WHERE tenant_id = ${tenantId}
        AND metadata @> ${JSON.stringify({ appId: "crm" })}::jsonb
    `)) as Array<{ name: string }>;
    const seenAgents = agentRows.map((r) => r.name).sort();
    const expectedAgentsSorted = [...expectedAgentNames].sort();
    expect(seenAgents).toEqual(expectedAgentsSorted);

    // 2 workflow templates by spec name (Email Sync, Calendar Check).
    const workflowRows = (await conn.db.execute(sql`
      SELECT name FROM workflows
      WHERE tenant_id = ${tenantId}
        AND metadata @> ${JSON.stringify({ appId: "crm" })}::jsonb
      ORDER BY name
    `)) as Array<{ name: string }>;
    const wfNames = workflowRows.map((r) => r.name);
    for (const expected of expectedWorkflowNames) {
      expect(wfNames).toContain(expected);
    }

    // 1 default pipeline + 7 stages from the onTenantCreated hook.
    const pipelineRows = (await conn.db.execute(sql`
      SELECT id, name FROM m3_crm_pipelines
      WHERE tenant_id = ${tenantId} AND is_default = true
    `)) as Array<{ id: string; name: string }>;
    expect(pipelineRows).toHaveLength(1);
    expect(pipelineRows[0]?.name).toBe("Sales Pipeline");

    const stageRows = (await conn.db.execute(sql`
      SELECT name, sort_order FROM m3_crm_pipeline_stages
      WHERE pipeline_id = ${pipelineRows[0]!.id}
      ORDER BY sort_order
    `)) as Array<{ name: string; sort_order: number }>;
    expect(stageRows.map((r) => r.name)).toEqual(stageNames);

    appendReport(
      `\n## M3 — Seeding (${new Date().toISOString()})\n\n` +
        `| Item | Expected | Actual |\n|---|---|---|\n` +
        `| agents | ${expectedAgentNames.length} | ${agentRows.length} |\n` +
        `| workflows (spec set) | ${expectedWorkflowNames.length} | ${expectedWorkflowNames.filter((n) => wfNames.includes(n)).length} |\n` +
        `| default pipelines | 1 | ${pipelineRows.length} |\n` +
        `| pipeline stages | ${stageNames.length} | ${stageRows.length} |\n`,
    );
  });
});
