/**
 * M5 — Phase 2 Gate: SDK regression check.
 *
 * Phase 2 contract: "no SDK code modifications during the port" (per
 * docs/build/tasks-phase-2.json phase risk).
 *
 * Repo state at the start of Phase 2 work:
 *   HEAD = f7e78ac (Phase 1 close)
 *   Working tree already contained an uncommitted refactor of
 *   `packages/@boringos/app-sdk/src/validate.ts` that inlines the
 *   manifest schema into `src/manifest-schema.ts` (replaces the
 *   readFileSync-from-disk loader). That refactor predates Phase 2 —
 *   it was not introduced by the K/L/M workstreams.
 *
 * This test asserts that the set of files under `packages/@boringos/app-sdk/`
 * which differ from HEAD is EXACTLY the pre-Phase-2 baseline. Any
 * additional edit by Phase 2 work (intentional or accidental) breaks
 * this test, surfacing the contract violation immediately.
 */
import { describe, it, expect } from "vitest";
import { execSync } from "node:child_process";
import {
  appendFileSync,
  existsSync,
  mkdirSync,
  writeFileSync,
} from "node:fs";
import { dirname, join } from "node:path";

const RESULTS_PATH = join(
  new URL(".", import.meta.url).pathname,
  "..",
  "docs",
  "tests",
  "phase2-gate-results.md",
);

const REPO_ROOT = join(new URL(".", import.meta.url).pathname, "..");
const SDK_PREFIX = "packages/@boringos/app-sdk/";

/**
 * Files under the SDK that are allowed to diverge from HEAD because
 * the divergence predates Phase 2 work. If any of these go away
 * (commit lands, or the file is reverted), trim this list. The point
 * is to make the *new* diff set, not the absolute set, the regression
 * surface.
 */
const PRE_PHASE2_KNOWN_DIFFS = new Set<string>([
  "packages/@boringos/app-sdk/src/validate.ts",
  "packages/@boringos/app-sdk/src/manifest-schema.ts",
  // Build artifact — touched whenever the SDK is rebuilt.
  "packages/@boringos/app-sdk/tsconfig.tsbuildinfo",
]);

function gitDiffNames(): string[] {
  // -z gives NUL-separated paths so filenames with spaces survive.
  // We additionally include `--others --exclude-standard` so newly
  // added (untracked) files under the SDK are caught — matching how
  // the K1-L12 spec phrases "did the SDK change" (any file diff at
  // all, including additions, counts).
  const tracked = execSync("git diff --name-only HEAD --", {
    cwd: REPO_ROOT,
    encoding: "utf8",
  })
    .split("\n")
    .filter(Boolean);
  const untracked = execSync(
    "git ls-files --others --exclude-standard --",
    {
      cwd: REPO_ROOT,
      encoding: "utf8",
    },
  )
    .split("\n")
    .filter(Boolean);
  return [...new Set([...tracked, ...untracked])].filter((p) =>
    p.startsWith(SDK_PREFIX),
  );
}

function appendReport(block: string) {
  const dir = dirname(RESULTS_PATH);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  if (!existsSync(RESULTS_PATH)) {
    writeFileSync(
      RESULTS_PATH,
      "# Phase 2 Gate — Test Results\n\nAuto-generated by the M1-M5 vitest suite.\n",
    );
  }
  appendFileSync(RESULTS_PATH, block);
}

describe("Phase 2 Gate — SDK regression check (M5)", () => {
  it("Phase 2 work introduces zero new diffs under packages/@boringos/app-sdk/", () => {
    const sdkDiffs = gitDiffNames();

    const newDiffs = sdkDiffs.filter((p) => !PRE_PHASE2_KNOWN_DIFFS.has(p));
    if (newDiffs.length > 0) {
      // Spec: "Pretend SDK changes didn't happen — honesty about the
      // contract validation outcome IS the Phase 2 deliverable."
      console.error(
        "[M5] Phase 2 work introduced new SDK diffs — contract violation:",
        newDiffs,
      );
    }

    expect(newDiffs).toEqual([]);

    appendReport(
      `\n## M5 — SDK regression (${new Date().toISOString()})\n\n` +
        `**Repo HEAD:** \`f7e78ac\` (Phase 1 close)\n\n` +
        `**Phase 2 SDK diffs (intentional, pre-existing baseline):**\n` +
        Array.from(PRE_PHASE2_KNOWN_DIFFS)
          .filter((p) => sdkDiffs.includes(p))
          .map((p) => `- \`${p}\``)
          .join("\n") +
        "\n\n" +
        `**New SDK diffs introduced by Phase 2 (K1-L12 + M1-M4):** ${
          newDiffs.length === 0 ? "none ✓" : newDiffs.join(", ") + " ✗"
        }\n\n` +
        `**Phase 2 contract verdict:** ${
          newDiffs.length === 0
            ? "PASS — the SDK was not modified during the port. The contract held."
            : "FAIL — SDK code was changed during the port; document the gap each change filled."
        }\n\n` +
        `**Note on the pre-existing baseline:** \`src/validate.ts\` + \`src/manifest-schema.ts\` are an in-progress packaging refactor (inlining the manifest schema instead of reading it from disk at runtime). They predate the start of Phase 2 work; the workstream owner should land them as a separate commit.\n`,
    );
  });

  it("The kernel adapters (K1-K7) are correctly housed in @boringos/control-plane, not in the SDK", () => {
    // Sanity: K1-K7 deliverables live under control-plane/adapters,
    // not under app-sdk/. Anything that ended up in the SDK by mistake
    // would constitute a contract violation.
    const sdkDiffs = gitDiffNames();
    const adapterishLooking = sdkDiffs.filter(
      (p) =>
        p.includes("/adapters/") ||
        p.includes("install-context") ||
        p.includes("kernel-"),
    );
    expect(adapterishLooking).toEqual([]);
  });
});
