/**
 * M4 — Phase 2 Gate: copilot picks up CRM context (agentDocs).
 *
 * After kernel install of the CRM-shaped fixture, the framework's
 * api-catalog context provider injects CRM's route docs into every
 * agent run's system prompt. Without CRM installed, the same catalog
 * has no CRM section.
 */
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { mkdtempSync, mkdirSync, rmSync, writeFileSync, appendFileSync, existsSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { sql } from "drizzle-orm";
import { Hono } from "hono";

import {
  createAppRouteRegistry,
  createKernelInstallContext,
  type ApiCatalogEntry,
} from "@boringos/control-plane";
import type { AppManifest, RouteRegistrar } from "@boringos/app-sdk";
import { defineApp } from "@boringos/app-sdk";
import { InstallRuntime } from "@boringos/shell/runtime/install-runtime.js";
import { createApiCatalogProvider } from "@boringos/agent";

const RESULTS_PATH = join(
  new URL(".", import.meta.url).pathname,
  "..",
  "docs",
  "tests",
  "phase2-gate-results.md",
);

let dataDir: string;
let conn: { db: any; close(): Promise<void> };
let tenantId: string;

beforeAll(async () => {
  const { createDatabase, createMigrationManager } = await import("@boringos/db");
  dataDir = mkdtempSync(join(tmpdir(), "bos-m4-"));
  conn = await createDatabase({
    embedded: true,
    dataDir: join(dataDir, "pg"),
    port: 5586,
  });
  await createMigrationManager(conn.db).apply();
  const inserted = await conn.db.execute(sql`
    INSERT INTO tenants (name, slug) VALUES ('M4', 'm4-test') RETURNING id
  `);
  tenantId = (inserted as any[])[0].id as string;
}, 120_000);

afterAll(async () => {
  await conn?.close();
  if (dataDir) rmSync(dataDir, { recursive: true, force: true });
});

const crmManifest: AppManifest = {
  kind: "app",
  id: "crm",
  version: "0.0.1",
  name: "CRM",
  description: "M4 fixture",
  publisher: { name: "BoringOS", verified: true },
  minRuntime: "1.0.0",
  license: "BUSL-1.1",
  hosting: "in-process",
  entityTypes: [],
  ui: { entry: "dist/ui.js" },
  capabilities: ["routes:register"],
};

/**
 * Mirrors the CRM's actual `crmAgentDocs(callbackUrl)` string shape
 * from boringos-crm/packages/server/src/context-providers/crm-schema.ts
 * — a single concatenated docs blob with sections for each route group
 * (contacts, companies, deals, pipelines, activities, inbox, memory,
 * profile, actions). The framework's api-catalog provider doesn't care
 * about the structure of the markdown, only that the docs string is
 * registered under the correct mount path.
 */
function fakeCrmAgentDocs(callbackUrl: string): string {
  return `You are the copilot for a CRM application. You have access to the following data and endpoints. Every call requires the \`X-Tenant-Id\` header.

#### Entities & Endpoints

##### Contacts
GET ${callbackUrl}/api/crm/contacts
POST ${callbackUrl}/api/crm/contacts

##### Companies
GET ${callbackUrl}/api/crm/companies

##### Deals
GET ${callbackUrl}/api/crm/deals
POST ${callbackUrl}/api/crm/deals

##### Pipelines
GET ${callbackUrl}/api/crm/pipelines

##### Activities
GET ${callbackUrl}/api/crm/activities`;
}

function appendReport(block: string) {
  const dir = dirname(RESULTS_PATH);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  if (!existsSync(RESULTS_PATH)) {
    writeFileSync(
      RESULTS_PATH,
      "# Phase 2 Gate — Test Results\n\nAuto-generated by the M1-M5 vitest suite.\n",
    );
  }
  appendFileSync(RESULTS_PATH, block);
}

async function buildPromptFragmentFromCatalog(
  catalog: ApiCatalogEntry[],
  callbackUrl: string,
): Promise<string> {
  const provider = createApiCatalogProvider(catalog);
  const event = { callbackUrl } as unknown as Parameters<typeof provider.provide>[0];
  return (await provider.provide(event)) ?? "";
}

describe("Phase 2 Gate — copilot context (M4)", () => {
  it("after install, the api-catalog provider injects CRM route docs into the prompt", async () => {
    const coreApp = new Hono();
    const routeRegistry = createAppRouteRegistry();
    routeRegistry.attachTo(coreApp);
    const shellRuntime = new InstallRuntime();

    const kernel = createKernelInstallContext({
      db: conn.db,
      routeRegistry,
      slotRuntime: {
        installApp: (a) => shellRuntime.installApp(a),
        uninstallApp: (id) => shellRuntime.uninstallApp(id),
      },
      events: { emit: () => {} },
    });

    const routes: RouteRegistrar = (router) => {
      const sub = router as Hono;
      sub.get("/contacts", (c) => c.json({ contacts: [] }));
      sub.get("/deals", (c) => c.json({ deals: [] }));
    };
    routes.agentDocs = fakeCrmAgentDocs;

    await kernel.installApp({
      manifest: crmManifest,
      tenantId,
      definition: defineApp({ id: "crm", routes }),
    });

    const catalog = kernel.getApiCatalog();
    expect(catalog.find((c) => c.path === "/api/crm")).toBeTruthy();

    const prompt = await buildPromptFragmentFromCatalog(catalog, "http://localhost:3000");

    // The fragment carries the App APIs heading + CRM-specific entries.
    expect(prompt).toContain("## App APIs");
    expect(prompt).toContain("### Mount: `/api/crm`");
    for (const tag of ["Contacts", "Deals", "Companies", "Pipelines", "Activities"]) {
      expect(prompt).toContain(tag);
    }
    expect(prompt).toContain("http://localhost:3000/api/crm/deals");

    appendReport(
      `\n## M4 — Copilot context (${new Date().toISOString()})\n\n` +
        `| Check | Status |\n|---|---|\n` +
        `| catalog has /api/crm entry | ✓ |\n` +
        `| prompt includes CRM mount header | ✓ |\n` +
        `| prompt mentions Contacts/Deals/Companies/Pipelines/Activities | ✓ |\n` +
        `| docs render against the supplied callback URL | ✓ |\n`,
    );
  });

  it("without CRM installed, the catalog has no CRM section", async () => {
    const coreApp = new Hono();
    const routeRegistry = createAppRouteRegistry();
    routeRegistry.attachTo(coreApp);

    const kernel = createKernelInstallContext({
      db: conn.db,
      routeRegistry,
      slotRuntime: {
        installApp: () => ({ appId: "noop" }),
        uninstallApp: () => {},
      },
      events: { emit: () => {} },
    });

    const catalog = kernel.getApiCatalog();
    expect(catalog.find((c) => c.path === "/api/crm")).toBeUndefined();

    const prompt = await buildPromptFragmentFromCatalog(catalog, "http://localhost:3000");
    expect(prompt).toBe("");
  });
});
