/**
 * M2 — Phase 2 Gate: slot contributions visible immediately after install.
 *
 * Verifies that the kernel install pipeline (K7) hands the app's
 * UIDefinition to the shell-side InstallRuntime synchronously inside the
 * install transaction, so the SlotRegistry exposes every CRM contribution
 * (nav pages, entity actions, settings panels) one tick after install
 * resolves.
 */
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { mkdtempSync, rmSync, existsSync, mkdirSync, writeFileSync, appendFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { sql } from "drizzle-orm";
import { Hono } from "hono";

import {
  createAppRouteRegistry,
  createKernelInstallContext,
} from "@boringos/control-plane";
import type { AppManifest, UIDefinition } from "@boringos/app-sdk";
import { defineApp, defineUI } from "@boringos/app-sdk";
import { InstallRuntime } from "@boringos/shell/runtime/install-runtime.js";
import { SlotRegistry } from "@boringos/shell/slots/registry.js";

const RESULTS_PATH = join(
  new URL(".", import.meta.url).pathname,
  "..",
  "docs",
  "tests",
  "phase2-gate-results.md",
);

let dataDir: string;
let conn: { db: any; close(): Promise<void> };
let tenantId: string;

beforeAll(async () => {
  const { createDatabase, createMigrationManager } = await import("@boringos/db");
  dataDir = mkdtempSync(join(tmpdir(), "bos-m2-"));
  conn = await createDatabase({
    embedded: true,
    dataDir: join(dataDir, "pg"),
    port: 5588,
  });
  await createMigrationManager(conn.db).apply();
  const inserted = await conn.db.execute(sql`
    INSERT INTO tenants (name, slug) VALUES ('M2', 'm2-test') RETURNING id
  `);
  tenantId = (inserted as any[])[0].id as string;
}, 120_000);

afterAll(async () => {
  await conn?.close();
  if (dataDir) rmSync(dataDir, { recursive: true, force: true });
});

const StubComponent = (() => null) as any;

const crmManifest: AppManifest = {
  kind: "app",
  id: "crm",
  version: "0.0.1",
  name: "CRM",
  description: "M2 fixture",
  publisher: { name: "BoringOS", verified: true },
  minRuntime: "1.0.0",
  license: "BUSL-1.1",
  hosting: "in-process",
  entityTypes: [
    { id: "crm_deal", label: "Deal", shareable: true },
  ],
  ui: { entry: "dist/ui.js" },
  capabilities: ["slots:nav", "slots:entity.action", "slots:settings.panel"],
};

const crmUI: UIDefinition = defineUI({
  pages: {
    pipeline: { id: "pipeline", component: StubComponent },
    deals: { id: "deals", component: StubComponent },
    contacts: { id: "contacts", component: StubComponent },
    companies: { id: "companies", component: StubComponent },
  },
  entityActions: {
    "send-followup": {
      id: "send-followup",
      entity: "crm_deal",
      label: "Send follow-up",
      invoke: async () => {},
    },
    "run-analyst": {
      id: "run-analyst",
      entity: "crm_deal",
      label: "Run analyst",
      invoke: async () => {},
    },
    "mark-won": {
      id: "mark-won",
      entity: "crm_deal",
      label: "Mark won",
      invoke: async () => {},
    },
    "mark-lost": {
      id: "mark-lost",
      entity: "crm_deal",
      label: "Mark lost",
      invoke: async () => {},
    },
  },
  settingsPanels: {
    "pipeline-config": {
      id: "pipeline-config",
      label: "Pipeline configuration",
      component: StubComponent,
    },
  },
});

function appendReport(block: string) {
  const dir = dirname(RESULTS_PATH);
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  if (!existsSync(RESULTS_PATH)) {
    writeFileSync(
      RESULTS_PATH,
      "# Phase 2 Gate — Test Results\n\nAuto-generated by the M1-M5 vitest suite.\n",
    );
  }
  appendFileSync(RESULTS_PATH, block);
}

describe("Phase 2 Gate — slot visibility (M2)", () => {
  it("after install, slotRegistry reports all CRM nav, action, and settings contributions", async () => {
    const slotRegistry = new SlotRegistry();
    const shellRuntime = new InstallRuntime(slotRegistry);
    const coreApp = new Hono();
    const routeRegistry = createAppRouteRegistry();
    routeRegistry.attachTo(coreApp);

    const kernel = createKernelInstallContext({
      db: conn.db,
      routeRegistry,
      slotRuntime: {
        installApp: (a) => shellRuntime.installApp(a),
        uninstallApp: (id) => shellRuntime.uninstallApp(id),
      },
      events: { emit: () => {} },
    });

    await kernel.installApp({
      manifest: crmManifest,
      tenantId,
      definition: defineApp({ id: "crm" }),
      ui: crmUI,
    });

    const pageIds = slotRegistry.list("pages").map((c) => `${c.appId}.${c.slotId}`).sort();
    expect(pageIds).toEqual([
      "crm.companies",
      "crm.contacts",
      "crm.deals",
      "crm.pipeline",
    ]);

    const dealActions = slotRegistry.list("entityActions", { appId: "crm" });
    expect(dealActions.map((c) => c.slotId).sort()).toEqual([
      "mark-lost",
      "mark-won",
      "run-analyst",
      "send-followup",
    ]);
    expect(
      dealActions.every((c) => (c.slot as { entity: string }).entity === "crm_deal"),
    ).toBe(true);

    const settingsPanels = slotRegistry.list("settingsPanels", { appId: "crm" });
    expect(settingsPanels.map((c) => c.slotId)).toEqual(["pipeline-config"]);

    appendReport(
      `\n## M2 — Slot visibility (${new Date().toISOString()})\n\n` +
        `| Family | Count | Ids |\n|---|---|---|\n` +
        `| pages | ${pageIds.length} | ${pageIds.join(", ")} |\n` +
        `| entityActions[crm_deal] | ${dealActions.length} | ${dealActions
          .map((c) => c.slotId)
          .sort()
          .join(", ")} |\n` +
        `| settingsPanels | ${settingsPanels.length} | ${settingsPanels
          .map((c) => c.slotId)
          .join(", ")} |\n`,
    );
  });
});
